### PR TITLE
Added Jekyll and put your content in a post

### PR DESCRIPTION
**Pull request by dtuite**

### CODE REVIEW

**Comment by wiktorschmidt** [comment]
wow - this looks good. Do you think we can merge it with the current twitter/bootstrap version?

**Comment by dtuite** [comment]
Yeah shouldn't be an issue. I'm already using bootstrap on my own blog. I'm going to add a post about my presentation on Tuesday now so I can have a look at it now.

**Comment by dtuite** [comment]
I don't get it, how do I merge this manually so that I can integrate your changes to the index.html?

**Comment by wiktorschmidt** [comment]
Cool... I think if you merge it you should go ahead and push to master :)

**Comment by wiktorschmidt** [comment]
you need to git merge dublinjs master (add another remote to your local repo)

**Comment by dtuite** [comment]
Yeah ok I can see the conflicts on my local repo.

The way I set up Jekyll, each post that people make get's own permalinked page, then on the homepage I was just displaying a snippet from each of the 5 most recent posts. 

Is this what we want? Or should just I just leave the full, latest post on the homepage?

The thing about it is that I think I might break the nav links you have in the header etc?

**Comment by wiktorschmidt** [comment]
I think its nice to have last post on homepage and links to previous below. I can fix the nav.

**Comment by dtuite** [comment]
Ok I'll give that a shot now and push it.

**Pull request merged**
